### ISSUE TITLE
Author sort is broken

### ISSUE THREAD

**Issue by straill** [UMNLibraries/betapub#13]
Sorting by author results in an error message:

RSolr::Error::Http - 400 Bad Request Error: 'can not sort on multivalued field: authors','code'=>400}}

**Comment by gsormsby** [comment]
We determined that the conceptual problems with sorting on a multiple value field (or more accurately, with sorting on one arbitrary author among many co-authors) were compelling enough to recommend removing the "sort by author" feature. Facets handle the problem of finding a specific authors works much more elegantly and less problematically. So the "fix" for this issue is removing the feature.
